name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{secrets.DOCKERHUB_USERNAME }}
        password: ${{secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5.3.0
      with:
        push: true
        tags: rapega/go-app:${{ github.sha }} , rapega/go-app:latest

  update:
    name: update helm manifests
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Update Image Tag Values
      run: |
        chart_dir="chart"
        new_image_tag=${{github.sha}}
        # Update the values.yaml file with the new image tag
        sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values.yaml"
    
    - name: commit the changes made
      uses: actions-x/commit@v6
      email: ${{ github.actor }}@localhost
      
